language: python

python:
  - 3.6

services: postgresql

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip3 install -r requirements/local.txt
  - pip3 install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE sdu_beta_career;" -U postgres
  - psql -c "CREATE ROLE sdu_beta_career with password 'sdu_beta_career';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE sdu_beta_career to sdu_beta_career;" -U postgres
  - psql -c "alter user sdu_beta_career login createdb;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
